from __future__ import annotations

from archetexture.core.operations import (
    OperationDefinition,
    OperationDefinitionSet,
    OperationType,
    Seamlessness,
)
from archetexture.core.parameters import ParameterSpec, ParameterType
from archetexture.generators import basic as generators
from archetexture.generators import noise as noise_generators
from archetexture.generators import patterns as pattern_generators
from archetexture.transforms import basic as transforms
from archetexture.transforms import spatial as spatial_transforms
from archetexture.transforms import tonal as tonal_transforms

REGISTRY = OperationDefinitionSet()


def _spec(
    identifier: str,
    name: str,
    kind: ParameterType,
    default,
    minimum: float,
    maximum: float,
    step: float,
    *,
    description: str = "",
    allows_modulation: bool = True,
) -> ParameterSpec:
    return ParameterSpec(
        identifier,
        name,
        kind,
        default=default,
        min_value=minimum,
        max_value=maximum,
        step=step,
        description=description,
        allows_modulation=allows_modulation,
    )


def builtin_definitions() -> tuple[OperationDefinition, ...]:
    return (
        OperationDefinition(
            "generator.constant",
            1,
            "Constant",
            "Generator",
            "Produces a constant scalar field.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (_spec("value", "Value", ParameterType.FLOAT, 0.5, 0.0, 1.0, 0.01),),
            Seamlessness.INHERENT,
            generators.constant,
        ),
        OperationDefinition(
            "generator.white_noise",
            1,
            "White Noise",
            "Generator",
            "Deterministic uniform scalar noise.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                ParameterSpec(
                    "seed",
                    "Seed",
                    ParameterType.SEED,
                    default=0,
                    min_value=0,
                    max_value=2**31 - 1,
                    step=1,
                    allows_modulation=False,
                ),
            ),
            Seamlessness.UNKNOWN,
            generators.white_noise,
        ),
        OperationDefinition(
            "generator.linear_gradient",
            1,
            "Linear Gradient",
            "Generator",
            "Projects a normalized gradient along the selected angle.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (_spec("angle", "Angle", ParameterType.ANGLE, 0.0, 0.0, 360.0, 1.0),),
            Seamlessness.UNKNOWN,
            generators.linear_gradient,
        ),
        OperationDefinition(
            "generator.radial_gradient",
            1,
            "Radial Gradient",
            "Generator",
            "Produces a centered falloff whose radius is measured against the image width.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (_spec("radius", "Radius", ParameterType.FLOAT, 0.5, 0.01, 1.0, 0.01),),
            Seamlessness.UNKNOWN,
            generators.radial_gradient,
        ),
        OperationDefinition(
            "generator.value_noise",
            1,
            "Value Noise",
            "Noise",
            "Smooth deterministic lattice noise with spatial offsets.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec(
                    "seed", "Seed", ParameterType.SEED, 17, 0, 2**31 - 1, 1, allows_modulation=False
                ),
                _spec(
                    "scale",
                    "Scale",
                    ParameterType.FLOAT,
                    5.0,
                    0.5,
                    48.0,
                    0.5,
                    description="Cells across the image's shorter side.",
                ),
                _spec("offset_x", "Offset X", ParameterType.FLOAT, 0.0, -20.0, 20.0, 0.1),
                _spec("offset_y", "Offset Y", ParameterType.FLOAT, 0.0, -20.0, 20.0, 0.1),
            ),
            Seamlessness.UNKNOWN,
            noise_generators.value_noise,
        ),
        OperationDefinition(
            "generator.fractal_noise",
            1,
            "Fractal Noise",
            "Noise",
            "Layered smooth value noise for clouds, stone, and material variation.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec(
                    "seed", "Seed", ParameterType.SEED, 31, 0, 2**31 - 1, 1, allows_modulation=False
                ),
                _spec(
                    "scale",
                    "Scale",
                    ParameterType.FLOAT,
                    3.5,
                    0.5,
                    32.0,
                    0.5,
                    description="Base cells across the image's shorter side.",
                ),
                _spec(
                    "octaves", "Octaves", ParameterType.INTEGER, 5, 1, 8, 1, allows_modulation=False
                ),
                _spec(
                    "lacunarity",
                    "Lacunarity",
                    ParameterType.FLOAT,
                    2.0,
                    1.2,
                    4.0,
                    0.1,
                    allows_modulation=False,
                ),
                _spec(
                    "persistence",
                    "Persistence",
                    ParameterType.FLOAT,
                    0.5,
                    0.0,
                    0.95,
                    0.05,
                    allows_modulation=False,
                ),
                _spec("offset_x", "Offset X", ParameterType.FLOAT, 0.0, -20.0, 20.0, 0.1),
                _spec("offset_y", "Offset Y", ParameterType.FLOAT, 0.0, -20.0, 20.0, 0.1),
            ),
            Seamlessness.UNKNOWN,
            noise_generators.fractal_noise,
        ),
        OperationDefinition(
            "generator.turbulence",
            1,
            "Turbulence",
            "Noise",
            "Fractal noise with folded values for wispy, turbulent structure.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec(
                    "seed", "Seed", ParameterType.SEED, 47, 0, 2**31 - 1, 1, allows_modulation=False
                ),
                _spec(
                    "scale",
                    "Scale",
                    ParameterType.FLOAT,
                    3.0,
                    0.5,
                    32.0,
                    0.5,
                    description="Base cells across the image's shorter side.",
                ),
                _spec(
                    "octaves", "Octaves", ParameterType.INTEGER, 5, 1, 8, 1, allows_modulation=False
                ),
                _spec(
                    "lacunarity",
                    "Lacunarity",
                    ParameterType.FLOAT,
                    2.0,
                    1.2,
                    4.0,
                    0.1,
                    allows_modulation=False,
                ),
                _spec(
                    "persistence",
                    "Persistence",
                    ParameterType.FLOAT,
                    0.5,
                    0.0,
                    0.95,
                    0.05,
                    allows_modulation=False,
                ),
                _spec("offset_x", "Offset X", ParameterType.FLOAT, 0.0, -20.0, 20.0, 0.1),
                _spec("offset_y", "Offset Y", ParameterType.FLOAT, 0.0, -20.0, 20.0, 0.1),
            ),
            Seamlessness.UNKNOWN,
            noise_generators.turbulence,
        ),
        OperationDefinition(
            "generator.cellular",
            1,
            "Cellular",
            "Patterns",
            "Worley-style cells with nearest-distance and cell-edge outputs.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec(
                    "seed", "Seed", ParameterType.SEED, 59, 0, 2**31 - 1, 1, allows_modulation=False
                ),
                _spec(
                    "scale",
                    "Cell Density",
                    ParameterType.FLOAT,
                    7.0,
                    1.0,
                    48.0,
                    1.0,
                    allows_modulation=False,
                ),
                _spec(
                    "jitter",
                    "Jitter",
                    ParameterType.FLOAT,
                    0.8,
                    0.0,
                    1.0,
                    0.05,
                    allows_modulation=False,
                ),
                ParameterSpec(
                    "distance_mode",
                    "Distance Mode",
                    ParameterType.ENUM,
                    "nearest",
                    allows_modulation=False,
                    options=("nearest", "edge"),
                ),
            ),
            Seamlessness.UNKNOWN,
            noise_generators.cellular,
        ),
        OperationDefinition(
            "generator.seamless_value_noise",
            1,
            "Seamless Value Noise",
            "Seamless Noise",
            "Periodic smooth lattice noise with a fixed rectangular cell period.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec(
                    "seed",
                    "Seed",
                    ParameterType.SEED,
                    17,
                    0,
                    2**31 - 1,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "cells_x",
                    "Cells X",
                    ParameterType.INTEGER,
                    8,
                    1,
                    128,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "cells_y",
                    "Cells Y",
                    ParameterType.INTEGER,
                    8,
                    1,
                    128,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "offset_x",
                    "Offset X",
                    ParameterType.FLOAT,
                    0.0,
                    -64.0,
                    64.0,
                    0.1,
                    allows_modulation=False,
                ),
                _spec(
                    "offset_y",
                    "Offset Y",
                    ParameterType.FLOAT,
                    0.0,
                    -64.0,
                    64.0,
                    0.1,
                    allows_modulation=False,
                ),
            ),
            Seamlessness.INHERENT,
            noise_generators.seamless_value_noise,
        ),
        OperationDefinition(
            "generator.seamless_fractal_noise",
            1,
            "Seamless Fractal Noise",
            "Seamless Noise",
            "Periodic multi-octave value noise with integer lacunarity.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec(
                    "seed",
                    "Seed",
                    ParameterType.SEED,
                    31,
                    0,
                    2**31 - 1,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "cells_x",
                    "Cells X",
                    ParameterType.INTEGER,
                    4,
                    1,
                    64,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "cells_y",
                    "Cells Y",
                    ParameterType.INTEGER,
                    4,
                    1,
                    64,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "octaves",
                    "Octaves",
                    ParameterType.INTEGER,
                    5,
                    1,
                    8,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "lacunarity",
                    "Lacunarity",
                    ParameterType.INTEGER,
                    2,
                    2,
                    4,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "persistence",
                    "Persistence",
                    ParameterType.FLOAT,
                    0.5,
                    0.0,
                    0.95,
                    0.05,
                    allows_modulation=False,
                ),
                _spec(
                    "offset_x",
                    "Offset X",
                    ParameterType.FLOAT,
                    0.0,
                    -64.0,
                    64.0,
                    0.1,
                    allows_modulation=False,
                ),
                _spec(
                    "offset_y",
                    "Offset Y",
                    ParameterType.FLOAT,
                    0.0,
                    -64.0,
                    64.0,
                    0.1,
                    allows_modulation=False,
                ),
            ),
            Seamlessness.INHERENT,
            noise_generators.seamless_fractal_noise,
        ),
        OperationDefinition(
            "generator.seamless_turbulence",
            1,
            "Seamless Turbulence",
            "Seamless Noise",
            "Folded periodic multi-octave value noise.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec(
                    "seed",
                    "Seed",
                    ParameterType.SEED,
                    47,
                    0,
                    2**31 - 1,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "cells_x",
                    "Cells X",
                    ParameterType.INTEGER,
                    4,
                    1,
                    64,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "cells_y",
                    "Cells Y",
                    ParameterType.INTEGER,
                    4,
                    1,
                    64,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "octaves",
                    "Octaves",
                    ParameterType.INTEGER,
                    5,
                    1,
                    8,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "lacunarity",
                    "Lacunarity",
                    ParameterType.INTEGER,
                    2,
                    2,
                    4,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "persistence",
                    "Persistence",
                    ParameterType.FLOAT,
                    0.5,
                    0.0,
                    0.95,
                    0.05,
                    allows_modulation=False,
                ),
                _spec(
                    "offset_x",
                    "Offset X",
                    ParameterType.FLOAT,
                    0.0,
                    -64.0,
                    64.0,
                    0.1,
                    allows_modulation=False,
                ),
                _spec(
                    "offset_y",
                    "Offset Y",
                    ParameterType.FLOAT,
                    0.0,
                    -64.0,
                    64.0,
                    0.1,
                    allows_modulation=False,
                ),
            ),
            Seamlessness.INHERENT,
            noise_generators.seamless_turbulence,
        ),
        OperationDefinition(
            "generator.seamless_cellular",
            1,
            "Seamless Cellular",
            "Seamless Patterns",
            "Periodic Worley cells with nearest-distance and cell-edge outputs.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec(
                    "seed",
                    "Seed",
                    ParameterType.SEED,
                    59,
                    0,
                    2**31 - 1,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "cells_x",
                    "Cells X",
                    ParameterType.INTEGER,
                    8,
                    1,
                    128,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "cells_y",
                    "Cells Y",
                    ParameterType.INTEGER,
                    8,
                    1,
                    128,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "jitter",
                    "Jitter",
                    ParameterType.FLOAT,
                    0.8,
                    0.0,
                    1.0,
                    0.05,
                    allows_modulation=False,
                ),
                ParameterSpec(
                    "distance_mode",
                    "Distance Mode",
                    ParameterType.ENUM,
                    "nearest",
                    allows_modulation=False,
                    options=("nearest", "edge"),
                ),
            ),
            Seamlessness.INHERENT,
            noise_generators.seamless_cellular,
        ),
        OperationDefinition(
            "generator.bands",
            1,
            "Bands / Wave",
            "Patterns",
            "Oriented periodic stripes with sine, triangle, saw, or square profiles.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec("frequency", "Frequency", ParameterType.FLOAT, 6.0, 0.5, 64.0, 0.5),
                _spec("angle", "Angle", ParameterType.ANGLE, 0.0, 0.0, 360.0, 1.0),
                _spec("phase", "Phase", ParameterType.FLOAT, 0.0, 0.0, 1.0, 0.01),
                ParameterSpec(
                    "waveform",
                    "Waveform",
                    ParameterType.ENUM,
                    "sine",
                    allows_modulation=False,
                    options=("sine", "triangle", "saw", "square"),
                ),
            ),
            Seamlessness.UNKNOWN,
            pattern_generators.bands,
        ),
        OperationDefinition(
            "generator.checker_grid",
            1,
            "Checker / Grid",
            "Patterns",
            "Regular checker cells or thin wrapping grid lines.",
            OperationType.GENERATOR,
            (),
            "scalar",
            (
                _spec(
                    "cells_x",
                    "Cells X",
                    ParameterType.INTEGER,
                    8,
                    1,
                    96,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "cells_y",
                    "Cells Y",
                    ParameterType.INTEGER,
                    8,
                    1,
                    96,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "offset_x",
                    "Offset X",
                    ParameterType.FLOAT,
                    0.0,
                    -1.0,
                    1.0,
                    0.01,
                    allows_modulation=False,
                ),
                _spec(
                    "offset_y",
                    "Offset Y",
                    ParameterType.FLOAT,
                    0.0,
                    -1.0,
                    1.0,
                    0.01,
                    allows_modulation=False,
                ),
                ParameterSpec(
                    "pattern",
                    "Pattern",
                    ParameterType.ENUM,
                    "checker",
                    allows_modulation=False,
                    options=("checker", "grid"),
                ),
                _spec(
                    "line_width",
                    "Line Width",
                    ParameterType.FLOAT,
                    0.08,
                    0.01,
                    0.3,
                    0.01,
                    allows_modulation=False,
                ),
            ),
            Seamlessness.WRAP_CAPABLE,
            pattern_generators.checker_grid,
        ),
        OperationDefinition(
            "transform.invert",
            1,
            "Invert",
            "Transform",
            "Inverts scalar values.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (),
            Seamlessness.PRESERVES,
            transforms.invert,
        ),
        OperationDefinition(
            "transform.threshold",
            1,
            "Threshold",
            "Transform",
            "Maps values at or above the threshold to one.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (_spec("threshold", "Threshold", ParameterType.FLOAT, 0.5, 0.0, 1.0, 0.01),),
            Seamlessness.PRESERVES,
            transforms.threshold,
        ),
        OperationDefinition(
            "transform.quantize",
            1,
            "Quantize",
            "Transform",
            "Quantizes normalized values to the selected number of levels.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (_spec("levels", "Levels", ParameterType.INTEGER, 8, 2, 256, 1),),
            Seamlessness.PRESERVES,
            transforms.quantize,
        ),
        OperationDefinition(
            "transform.levels",
            1,
            "Levels",
            "Tone",
            "Remaps input black/white and gamma into an output range.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (
                _spec("input_black", "Input Black", ParameterType.PERCENT, 0.1, 0.0, 1.0, 0.01),
                _spec("input_white", "Input White", ParameterType.PERCENT, 0.9, 0.0, 1.0, 0.01),
                _spec(
                    "gamma",
                    "Gamma",
                    ParameterType.FLOAT,
                    1.0,
                    0.1,
                    4.0,
                    0.05,
                    description="Values below one darken midtones; values above one brighten them.",
                ),
                _spec("output_black", "Output Black", ParameterType.PERCENT, 0.0, 0.0, 1.0, 0.01),
                _spec("output_white", "Output White", ParameterType.PERCENT, 1.0, 0.0, 1.0, 0.01),
            ),
            Seamlessness.PRESERVES,
            tonal_transforms.levels,
        ),
        OperationDefinition(
            "transform.brightness_contrast",
            1,
            "Brightness / Contrast",
            "Tone",
            "Brightness shifts values; contrast expands or compresses around mid-gray.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (
                _spec("brightness", "Brightness", ParameterType.FLOAT, 0.0, -1.0, 1.0, 0.01),
                _spec("contrast", "Contrast", ParameterType.FLOAT, 1.0, 0.0, 4.0, 0.05),
            ),
            Seamlessness.PRESERVES,
            tonal_transforms.brightness_contrast,
        ),
        OperationDefinition(
            "transform.blur",
            1,
            "Blur",
            "Detail",
            "Separable Gaussian blur with wrapped edges and float32 sampling.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (
                _spec(
                    "sigma",
                    "Sigma",
                    ParameterType.FLOAT,
                    1.0,
                    0.0,
                    8.0,
                    0.1,
                    allows_modulation=False,
                ),
            ),
            Seamlessness.PRESERVES,
            tonal_transforms.blur,
        ),
        OperationDefinition(
            "transform.sharpen",
            1,
            "Sharpen",
            "Detail",
            "Unsharp mask using the same wrapped Gaussian blur as Blur.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (
                _spec(
                    "amount",
                    "Amount",
                    ParameterType.FLOAT,
                    1.0,
                    0.0,
                    3.0,
                    0.05,
                    allows_modulation=False,
                ),
                _spec(
                    "sigma",
                    "Sigma",
                    ParameterType.FLOAT,
                    1.0,
                    0.1,
                    8.0,
                    0.1,
                    allows_modulation=False,
                ),
            ),
            Seamlessness.PRESERVES,
            tonal_transforms.sharpen,
        ),
        OperationDefinition(
            "transform.normalize",
            1,
            "Normalize",
            "Tone",
            "Maps the observed field minimum and maximum to zero and one.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (),
            Seamlessness.PRESERVES,
            tonal_transforms.normalize,
        ),
        OperationDefinition(
            "transform.offset",
            1,
            "Offset / Roll",
            "Spatial",
            "Moves a field in whole pixels and wraps the shifted edges.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (
                _spec(
                    "offset_x",
                    "Offset X",
                    ParameterType.INTEGER,
                    0,
                    -4096,
                    4096,
                    1,
                    allows_modulation=False,
                ),
                _spec(
                    "offset_y",
                    "Offset Y",
                    ParameterType.INTEGER,
                    0,
                    -4096,
                    4096,
                    1,
                    allows_modulation=False,
                ),
            ),
            Seamlessness.PRESERVES,
            spatial_transforms.offset,
        ),
        OperationDefinition(
            "transform.flip",
            1,
            "Flip",
            "Spatial",
            "Mirrors a scalar field horizontally or vertically.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (
                ParameterSpec(
                    "axis",
                    "Axis",
                    ParameterType.ENUM,
                    "horizontal",
                    allows_modulation=False,
                    options=("horizontal", "vertical"),
                ),
            ),
            Seamlessness.PRESERVES,
            spatial_transforms.flip,
        ),
        OperationDefinition(
            "transform.edge_detail",
            1,
            "Edge / Detail",
            "Detail",
            "Produces a normalized wrapped gradient-magnitude field.",
            OperationType.TRANSFORM,
            ("scalar",),
            "scalar",
            (),
            Seamlessness.PRESERVES,
            spatial_transforms.edge_detail,
        ),
    )


def register_builtin_operations(target: OperationDefinitionSet = REGISTRY) -> None:
    for definition in builtin_definitions():
        if definition.identifier not in target.definitions:
            target.register(definition)


register_builtin_operations()
